default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  port: 5432

development:
  <<: *default
  database: ecommerce_store_development